#!/usr/bin/env python3
import argparse
import os
import subprocess
from glob import glob

def main():
    parser = argparse.ArgumentParser()
    parser.add_argument('--c-no-optimization', default=False, type=bool)
    parser.add_argument('--c-std', default="c17", type=str)
    parser.add_argument('file', metavar='file', type=str, nargs=1, help='file to compile')
    args, unknown = parser.parse_known_args()
    clang_args = []
    if not args.c_no_optimization:
        clang_args.append("-O2")
    unzip = subprocess.run(["unzip", "-n", args.file[0] + "/code", "-d", args.file[0]])
    if unzip.returncode != 0:
        exit(zip.returncode)
    codes = glob(f"{args.file[0]}/**/*.c", recursive=True)
    clang = subprocess.run(["clang", *codes, "-o", args.file[0] + "/a.out", "-Qunused-arguments", "-lm", "-DONLINE_JUDGE", f"-std={args.c_std}", "-fmax-errors=255", *clang_args])
    exit(clang.returncode)

if __name__ == '__main__':
    main()
